// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TBHStats.Data;

#nullable disable

namespace TBHStats.Data.Migrations
{
    [DbContext(typeof(TbhStatsDbContext))]
    [Migration("20260531133324_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.16");

            modelBuilder.Entity("TBHStats.Core.Models.Act", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Acts", (string)null);
                });

            modelBuilder.Entity("TBHStats.Core.Models.ChestType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColorLabel")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("ChestTypes", (string)null);
                });

            modelBuilder.Entity("TBHStats.Core.Models.Difficulty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Difficulties", (string)null);
                });

            modelBuilder.Entity("TBHStats.Core.Models.HeroClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("HeroClasses", (string)null);
                });

            modelBuilder.Entity("TBHStats.Core.Models.MetricSample", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Gold")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("HeroDamage")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HeroLevel")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsReliable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NextLocation")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("NextLocation");

                    b.Property<int?>("StageId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TakenAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<long?>("Xp")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("XpToLevel")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StageId");

                    b.ToTable("MetricSamples", (string)null);
                });

            modelBuilder.Entity("TBHStats.Core.Models.MetricSampleChest", b =>
                {
                    b.Property<long>("MetricSampleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChestTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.HasKey("MetricSampleId", "ChestTypeId");

                    b.HasIndex("ChestTypeId");

                    b.ToTable("MetricSampleChests", (string)null);
                });

            modelBuilder.Entity("TBHStats.Core.Models.OptimizationProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SelectedMetric")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("OptimizationProfiles", (string)null);
                });

            modelBuilder.Entity("TBHStats.Core.Models.RoiCalibration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FieldKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<double>("H")
                        .HasColumnType("REAL");

                    b.Property<int>("OcrEngine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParseHint")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TabId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("W")
                        .HasColumnType("REAL");

                    b.Property<double>("X")
                        .HasColumnType("REAL");

                    b.Property<double>("Y")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("TabId");

                    b.ToTable("RoiCalibrations", (string)null);
                });

            modelBuilder.Entity("TBHStats.Core.Models.Stage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DifficultyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("ActId", "DifficultyId", "Number")
                        .IsUnique();

                    b.ToTable("Stages", (string)null);
                });

            modelBuilder.Entity("TBHStats.Core.Models.StageAggregate", b =>
                {
                    b.Property<int>("StageId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("AvgDurationSeconds")
                        .HasColumnType("REAL");

                    b.Property<double>("AvgGoldPerHour")
                        .HasColumnType("REAL");

                    b.Property<double>("AvgXpPerHour")
                        .HasColumnType("REAL");

                    b.Property<int>("BestDurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<double>("BestGoldPerHour")
                        .HasColumnType("REAL");

                    b.Property<double>("BestXpPerHour")
                        .HasColumnType("REAL");

                    b.Property<int>("RunCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("StageId");

                    b.ToTable("StageAggregates", (string)null);
                });

            modelBuilder.Entity("TBHStats.Core.Models.StageAggregateChestRate", b =>
                {
                    b.Property<int>("StageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChestTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("RatePerHour")
                        .HasColumnType("REAL");

                    b.HasKey("StageId", "ChestTypeId");

                    b.HasIndex("ChestTypeId");

                    b.ToTable("StageAggregateChestRates", (string)null);
                });

            modelBuilder.Entity("TBHStats.Core.Models.StageRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GoldGained")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPartial")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StageId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("XpGained")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StageId");

                    b.ToTable("StageRuns", (string)null);
                });

            modelBuilder.Entity("TBHStats.Core.Models.StageRunChest", b =>
                {
                    b.Property<long>("StageRunId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChestTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.HasKey("StageRunId", "ChestTypeId");

                    b.HasIndex("ChestTypeId");

                    b.ToTable("StageRunChests", (string)null);
                });

            modelBuilder.Entity("TBHStats.Core.Models.Tab", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDataSource")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecognitionText")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Tabs", (string)null);
                });

            modelBuilder.Entity("TBHStats.Core.Models.WidgetSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AlwaysOnTop")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Height")
                        .HasColumnType("REAL");

                    b.Property<int>("PollIntervalMs")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PosX")
                        .HasColumnType("REAL");

                    b.Property<double>("PosY")
                        .HasColumnType("REAL");

                    b.Property<int>("Theme")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Width")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("WidgetSettings", (string)null);
                });

            modelBuilder.Entity("TBHStats.Core.Models.MetricSample", b =>
                {
                    b.HasOne("TBHStats.Core.Models.Stage", null)
                        .WithMany()
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("TBHStats.Core.Models.MetricSampleChest", b =>
                {
                    b.HasOne("TBHStats.Core.Models.ChestType", null)
                        .WithMany()
                        .HasForeignKey("ChestTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TBHStats.Core.Models.MetricSample", null)
                        .WithMany("Chests")
                        .HasForeignKey("MetricSampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TBHStats.Core.Models.RoiCalibration", b =>
                {
                    b.HasOne("TBHStats.Core.Models.Tab", null)
                        .WithMany()
                        .HasForeignKey("TabId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("TBHStats.Core.Models.Stage", b =>
                {
                    b.HasOne("TBHStats.Core.Models.Act", null)
                        .WithMany()
                        .HasForeignKey("ActId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TBHStats.Core.Models.Difficulty", null)
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TBHStats.Core.Models.StageAggregate", b =>
                {
                    b.HasOne("TBHStats.Core.Models.Stage", null)
                        .WithOne()
                        .HasForeignKey("TBHStats.Core.Models.StageAggregate", "StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TBHStats.Core.Models.StageAggregateChestRate", b =>
                {
                    b.HasOne("TBHStats.Core.Models.ChestType", null)
                        .WithMany()
                        .HasForeignKey("ChestTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TBHStats.Core.Models.StageAggregate", null)
                        .WithMany("ChestRates")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TBHStats.Core.Models.StageRun", b =>
                {
                    b.HasOne("TBHStats.Core.Models.Stage", null)
                        .WithMany()
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("TBHStats.Core.Models.HeroSnapshot", "Hero", b1 =>
                        {
                            b1.Property<long>("StageRunId")
                                .HasColumnType("INTEGER");

                            b1.Property<long>("Damage")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Hero_Damage");

                            b1.Property<int>("HeroClassId")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Hero_HeroClassId");

                            b1.Property<int>("Level")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Hero_Level");

                            b1.HasKey("StageRunId");

                            b1.HasIndex("HeroClassId");

                            b1.ToTable("StageRuns");

                            b1.HasOne("TBHStats.Core.Models.HeroClass", null)
                                .WithMany()
                                .HasForeignKey("HeroClassId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("StageRunId");
                        });

                    b.Navigation("Hero")
                        .IsRequired();
                });

            modelBuilder.Entity("TBHStats.Core.Models.StageRunChest", b =>
                {
                    b.HasOne("TBHStats.Core.Models.ChestType", null)
                        .WithMany()
                        .HasForeignKey("ChestTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TBHStats.Core.Models.StageRun", "Run")
                        .WithMany("Chests")
                        .HasForeignKey("StageRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("TBHStats.Core.Models.MetricSample", b =>
                {
                    b.Navigation("Chests");
                });

            modelBuilder.Entity("TBHStats.Core.Models.StageAggregate", b =>
                {
                    b.Navigation("ChestRates");
                });

            modelBuilder.Entity("TBHStats.Core.Models.StageRun", b =>
                {
                    b.Navigation("Chests");
                });
#pragma warning restore 612, 618
        }
    }
}
